# Generated by Django 4.2.7 on 2023-11-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('complex_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finished', models.BooleanField()),
                ('space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_apartments', models.IntegerField()),
                ('number_of_houses', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to='complex_images/')),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_of_roof', models.CharField(max_length=100)),
            ],
        ),
    ]
