# Generated by Django 4.2.7 on 2023-11-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_ka', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('address_en', models.TextField(null=True)),
                ('address_ru', models.TextField(null=True)),
                ('address_ka', models.TextField(null=True)),
                ('Mobile', models.CharField(max_length=20)),
                ('Mobile_Home', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('companyweb', models.URLField(blank=True, null=True)),
                ('aboutcompany', models.TextField(blank=True, null=True)),
                ('aboutcompany_en', models.TextField(blank=True, null=True)),
                ('aboutcompany_ru', models.TextField(blank=True, null=True)),
                ('aboutcompany_ka', models.TextField(blank=True, null=True)),
                ('logocompany', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='company_background_images/')),
                ('facebook_page', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_ka', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('address_en', models.TextField(null=True)),
                ('address_ru', models.TextField(null=True)),
                ('address_ka', models.TextField(null=True)),
                ('price_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finished', models.BooleanField()),
                ('space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_apartments', models.IntegerField()),
                ('number_of_houses', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_of_roof', models.CharField(max_length=100)),
                ('type_of_roof_en', models.CharField(max_length=100, null=True)),
                ('type_of_roof_ru', models.CharField(max_length=100, null=True)),
                ('type_of_roof_ka', models.CharField(max_length=100, null=True)),
                ('text1', models.CharField(blank=True, max_length=300, null=True)),
                ('text1_en', models.CharField(blank=True, max_length=300, null=True)),
                ('text1_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text1_ka', models.CharField(blank=True, max_length=300, null=True)),
                ('text2', models.CharField(blank=True, max_length=300, null=True)),
                ('text2_en', models.CharField(blank=True, max_length=300, null=True)),
                ('text2_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text2_ka', models.CharField(blank=True, max_length=300, null=True)),
                ('text3', models.CharField(blank=True, max_length=300, null=True)),
                ('text3_en', models.CharField(blank=True, max_length=300, null=True)),
                ('text3_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text3_ka', models.CharField(blank=True, max_length=300, null=True)),
                ('text4', models.CharField(blank=True, max_length=300, null=True)),
                ('text4_en', models.CharField(blank=True, max_length=300, null=True)),
                ('text4_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text4_ka', models.CharField(blank=True, max_length=300, null=True)),
                ('text5', models.CharField(blank=True, max_length=300, null=True)),
                ('text5_en', models.CharField(blank=True, max_length=300, null=True)),
                ('text5_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text5_ka', models.CharField(blank=True, max_length=300, null=True)),
                ('text6', models.CharField(blank=True, max_length=300, null=True)),
                ('text6_en', models.CharField(blank=True, max_length=300, null=True)),
                ('text6_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text6_ka', models.CharField(blank=True, max_length=300, null=True)),
                ('text7', models.CharField(blank=True, max_length=300, null=True)),
                ('text7_en', models.CharField(blank=True, max_length=300, null=True)),
                ('text7_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text7_ka', models.CharField(blank=True, max_length=300, null=True)),
                ('text8', models.CharField(blank=True, max_length=300, null=True)),
                ('text8_en', models.CharField(blank=True, max_length=300, null=True)),
                ('text8_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text8_ka', models.CharField(blank=True, max_length=300, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='complex.company')),
            ],
        ),
        migrations.CreateModel(
            name='VIPComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_details', to='complex.complex')),
            ],
        ),
        migrations.CreateModel(
            name='ComplexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complex_images/')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_images', to='complex.complex')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('floor_number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='complex.complex')),
            ],
        ),
    ]
