# Generated by Django 4.2.7 on 2023-12-07 23:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_en', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Address_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ka', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Address_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ru', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Appartment_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('floor_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_available', models.BooleanField(default=True)),
                ('visibiliti', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='City_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_en', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_ka', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_ru', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('address_en', models.TextField()),
                ('aboutcompany_en', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logocompany', models.ImageField(blank=True, null=True, unique=True, upload_to='company_logos/')),
                ('background_image', models.ImageField(blank=True, null=True, unique=True, upload_to='company_background_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Company_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=255)),
                ('address_ka', models.TextField()),
                ('aboutcompany_ka', models.TextField(blank=True, null=True)),
                ('internal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_images')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=20)),
                ('Mobile_Home', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('companyweb', models.URLField(blank=True, null=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('topCompany', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('address_ru', models.TextField()),
                ('aboutcompany_ru', models.TextField(blank=True, null=True)),
                ('internal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_images')),
            ],
        ),
        migrations.CreateModel(
            name='Complex_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(unique=True, upload_to='complex_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Complex_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_complex_name', models.CharField(max_length=255, unique=True)),
                ('price_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finished', models.BooleanField()),
                ('visibiliti', models.BooleanField(default=True)),
                ('vipComplex', models.BooleanField(default=False)),
                ('space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_apartments', models.IntegerField()),
                ('number_of_houses', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('complex_level', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='District_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_en', models.CharField(max_length=50, unique=True)),
                ('city_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_en')),
            ],
        ),
        migrations.CreateModel(
            name='District_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_ka', models.CharField(max_length=50, unique=True)),
                ('city_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ka')),
            ],
        ),
        migrations.CreateModel(
            name='District_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_ru', models.CharField(max_length=50, unique=True)),
                ('city_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ru')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharentDistrict_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharentDistrict_en', models.CharField(max_length=50, unique=True)),
                ('city_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_en')),
                ('lang', models.ManyToManyField(to='complex.language')),
            ],
        ),
        migrations.CreateModel(
            name='PharentDistrict_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharentDistrict_ka', models.CharField(max_length=50, unique=True)),
                ('city_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ka')),
                ('lang', models.ManyToManyField(to='complex.language')),
            ],
        ),
        migrations.CreateModel(
            name='PharentDistrict_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharentDistrict_ru', models.CharField(max_length=50, unique=True)),
                ('city_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ru')),
                ('lang', models.ManyToManyField(to='complex.language')),
            ],
        ),
        migrations.CreateModel(
            name='Street_Name_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name_ru', models.CharField(max_length=50)),
                ('city_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ru')),
                ('district_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ru')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ru')),
            ],
        ),
        migrations.CreateModel(
            name='Street_Name_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name_ka', models.CharField(max_length=50)),
                ('city_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ka')),
                ('district_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ka')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka')),
            ],
        ),
        migrations.CreateModel(
            name='Street_Name_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name_en', models.CharField(max_length=50)),
                ('city_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_en')),
                ('district_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_en')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_en')),
            ],
        ),
        migrations.AddField(
            model_name='district_ru',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.AddField(
            model_name='district_ru',
            name='pharentDistrict_ru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ru'),
        ),
        migrations.AddField(
            model_name='district_ka',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.AddField(
            model_name='district_ka',
            name='pharentDistrict_ka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka'),
        ),
        migrations.AddField(
            model_name='district_en',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.AddField(
            model_name='district_en',
            name='pharentDistrict_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_en'),
        ),
        migrations.CreateModel(
            name='Complex_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name_ru', models.CharField(max_length=200, unique=True)),
                ('type_of_roof_ru', models.CharField(max_length=100)),
                ('address_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.address_ru')),
                ('company_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_ru')),
                ('complex_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_images')),
                ('internal_complex_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_names')),
            ],
        ),
        migrations.CreateModel(
            name='Complex_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name_ka', models.CharField(max_length=200, unique=True)),
                ('type_of_roof_ka', models.CharField(max_length=100)),
                ('address_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.address_ka')),
                ('company_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_ka')),
                ('complex_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_images')),
                ('internal_complex_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_names')),
            ],
        ),
        migrations.AddField(
            model_name='complex_images',
            name='internal_complex_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_names'),
        ),
        migrations.CreateModel(
            name='Complex_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name_en', models.CharField(max_length=200, unique=True)),
                ('type_of_roof_en', models.CharField(max_length=100)),
                ('address_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.address_en')),
                ('company_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_en')),
                ('complex_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_images')),
                ('internal_complex_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_names')),
            ],
        ),
        migrations.AddField(
            model_name='company_images',
            name='internal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_names'),
        ),
        migrations.AddField(
            model_name='company_en',
            name='internal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_images'),
        ),
        migrations.AddField(
            model_name='city_ru',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.AddField(
            model_name='city_ka',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.AddField(
            model_name='city_en',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.CreateModel(
            name='Appartment_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_ru', models.CharField(max_length=50)),
                ('internal_apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.appartment_names')),
            ],
        ),
        migrations.AddField(
            model_name='appartment_names',
            name='internal_apartment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_names'),
        ),
        migrations.CreateModel(
            name='Appartment_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_ka', models.CharField(max_length=50)),
                ('internal_apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.appartment_names')),
            ],
        ),
        migrations.CreateModel(
            name='Appartment_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='apartment_images/')),
                ('internal_apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.appartment_names')),
            ],
        ),
        migrations.CreateModel(
            name='Appartment_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_en', models.CharField(max_length=50)),
                ('internal_apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.appartment_names')),
            ],
        ),
        migrations.AddField(
            model_name='address_ru',
            name='city_ru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ru'),
        ),
        migrations.AddField(
            model_name='address_ru',
            name='district_ru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ru'),
        ),
        migrations.AddField(
            model_name='address_ru',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.AddField(
            model_name='address_ru',
            name='pharentDistrict_ru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ru'),
        ),
        migrations.AddField(
            model_name='address_ru',
            name='street_name_ru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.street_name_ru'),
        ),
        migrations.AddField(
            model_name='address_ka',
            name='city_ka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ka'),
        ),
        migrations.AddField(
            model_name='address_ka',
            name='district_ka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ka'),
        ),
        migrations.AddField(
            model_name='address_ka',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.AddField(
            model_name='address_ka',
            name='pharentDistrict_ka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka'),
        ),
        migrations.AddField(
            model_name='address_ka',
            name='street_name_ka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.street_name_ka'),
        ),
        migrations.AddField(
            model_name='address_en',
            name='city_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_en'),
        ),
        migrations.AddField(
            model_name='address_en',
            name='district_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_en'),
        ),
        migrations.AddField(
            model_name='address_en',
            name='lang',
            field=models.ManyToManyField(to='complex.language'),
        ),
        migrations.AddField(
            model_name='address_en',
            name='pharentDistrict_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_en'),
        ),
        migrations.AddField(
            model_name='address_en',
            name='street_name_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.street_name_en'),
        ),
    ]
