# Generated by Django 4.2.7 on 2024-01-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground_en',
            old_name='appartment_address_en',
            new_name='ground_address_en',
        ),
        migrations.RenameField(
            model_name='ground_en',
            old_name='appartment_name_en',
            new_name='ground_name_en',
        ),
        migrations.RenameField(
            model_name='ground_ru',
            old_name='appartment_address_ru',
            new_name='ground_address_ru',
        ),
        migrations.RenameField(
            model_name='ground_ru',
            old_name='appartment_name_ru',
            new_name='ground_name_ru',
        ),
        migrations.RemoveField(
            model_name='ground_en',
            name='appartment_images',
        ),
        migrations.RemoveField(
            model_name='ground_ru',
            name='appartment_images',
        ),
        migrations.AddField(
            model_name='ground_en',
            name='ground_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.ground_images'),
        ),
        migrations.AddField(
            model_name='ground_ru',
            name='ground_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.ground_images'),
        ),
    ]
