# Generated by Django 4.2.7 on 2024-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_names',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ground_names',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
