# Generated by Django 4.2.7 on 2024-01-12 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex_names',
            name='finished',
        ),
        migrations.AddField(
            model_name='complex_names',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex_names',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='rank',
            field=models.CharField(choices=[('A', 'Rank A'), ('B', 'Rank B'), ('C', 'Rank C'), ('D', 'Rank D'), ('E', 'Rank E')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='status',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Under Construction'), (3, 'Completed')], default=2),
        ),
    ]
