# Generated by Django 4.2.7 on 2024-01-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions_and_offers_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='promotions_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions_and_offers_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_promotion_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gift', models.CharField(blank=True, max_length=255, null=True)),
                ('installment', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_names')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions_and_offers_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name_ru', models.CharField(max_length=255, null=True)),
                ('about_ru', models.TextField(blank=True, null=True)),
                ('internal_promotion_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.promotions_and_offers_names')),
                ('promotion_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.promotions_and_offers_images')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions_and_offers_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name_ka', models.CharField(max_length=255, null=True)),
                ('about_ka', models.TextField(blank=True, null=True)),
                ('internal_promotion_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.promotions_and_offers_names')),
                ('promotion_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.promotions_and_offers_images')),
            ],
        ),
        migrations.AddField(
            model_name='promotions_and_offers_images',
            name='internal_promotion_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.promotions_and_offers_names'),
        ),
        migrations.CreateModel(
            name='Promotions_and_offers_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name_en', models.CharField(max_length=255, null=True)),
                ('about_en', models.TextField(blank=True, null=True)),
                ('internal_promotion_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.promotions_and_offers_names')),
                ('promotion_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.promotions_and_offers_images')),
            ],
        ),
    ]
