# Generated by Django 4.2.7 on 2023-11-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_details', to='complex.complex')),
            ],
        ),
    ]
