# Generated by Django 4.2.7 on 2023-12-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex_names',
            name='finished',
        ),
        migrations.AddField(
            model_name='complex_names',
            name='status',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Under Construction'), (3, 'Completed')], default=2),
        ),
    ]
