# Generated by Django 4.2.7 on 2023-11-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='aboutcompany_ka',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_ka',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='address_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='text1_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='text2_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='text3_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='text4_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='text5_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='text6_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='text7_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='text8_ka',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='type_of_roof_ka',
        ),
    ]
