# Generated by Django 4.2.7 on 2024-01-17 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Private_Appartment_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='private_apartment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Private_Appartment_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_private_apartment_name', models.CharField(max_length=50)),
                ('number_of_rooms', models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='studio', max_length=10)),
                ('status', models.CharField(choices=[('1', 'Newly renovated'), ('2', 'with old repairs'), ('3', 'to be repaired')], default='3', max_length=30)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('square_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor_number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('visibiliti', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='appartment_names',
            old_name='price',
            new_name='full_price',
        ),
        migrations.RemoveField(
            model_name='complex_names',
            name='finished',
        ),
        migrations.AddField(
            model_name='appartment_names',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appartment_names',
            name='square_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appartment_names',
            name='status',
            field=models.CharField(choices=[('1', 'Newly renovated'), ('2', 'with old repairs'), ('3', 'to be repaired')], default='3', max_length=30),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex_names',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='rank',
            field=models.CharField(choices=[('A', 'Rank A'), ('B', 'Rank B'), ('C', 'Rank C'), ('D', 'Rank D'), ('E', 'Rank E')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='status',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Under Construction'), (3, 'Completed')], default=2),
        ),
        migrations.AlterField(
            model_name='appartment_names',
            name='number_of_rooms',
            field=models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='studio', max_length=10),
        ),
        migrations.CreateModel(
            name='Private_Appartment_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_apartment_name_ru', models.CharField(max_length=100, null=True)),
                ('test_private_field_ru', models.CharField(max_length=100)),
                ('internal_private_apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_names')),
                ('private_apartment_address_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.address_ru')),
                ('private_apartment_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_images')),
            ],
        ),
        migrations.CreateModel(
            name='Private_Appartment_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_apartment_name_ka', models.CharField(max_length=100, null=True)),
                ('test_private_field_ka', models.CharField(max_length=100)),
                ('internal_private_apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_names')),
                ('private_apartment_address_ka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.address_ka')),
                ('private_apartment_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_images')),
            ],
        ),
        migrations.AddField(
            model_name='private_appartment_images',
            name='internal_private_apartment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_names'),
        ),
        migrations.CreateModel(
            name='Private_Appartment_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_apartment_name_en', models.CharField(max_length=100, null=True)),
                ('test_private_field_en', models.CharField(max_length=100)),
                ('internal_private_apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_names')),
                ('private_apartment_address_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.address_en')),
                ('private_apartment_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_images')),
            ],
        ),
    ]
