# Generated by Django 4.2.7 on 2023-11-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='complex_id',
        ),
        migrations.AddField(
            model_name='complex',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
