# Generated by Django 4.2.7 on 2024-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_en',
            name='catering_facility_en',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='concierge_service_en',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='elevator_type_en',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='schlangbaum_en',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='yard_description_en',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='catering_facility_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='concierge_service_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='elevator_type_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='schlangbaum_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='yard_description_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='catering_facility_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='concierge_service_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='elevator_type_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='schlangbaum_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='yard_description_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nearbyobject',
            name='metro',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nearbyobject',
            name='pharmacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nearbyobject',
            name='square',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nearbyobject',
            name='supermarket',
            field=models.BooleanField(default=True),
        ),
    ]
