# Generated by Django 4.2.7 on 2023-11-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='cities',
            field=models.ManyToManyField(related_name='langs', to='complex.city'),
        ),
    ]
