# Generated by Django 4.2.7 on 2023-12-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharentDistrict_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharentDistrict_ru', models.CharField(max_length=50, unique=True)),
                ('city_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ru')),
                ('lang', models.ManyToManyField(to='complex.language')),
            ],
        ),
        migrations.CreateModel(
            name='PharentDistrict_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharentDistrict_ka', models.CharField(max_length=50, unique=True)),
                ('city_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ka')),
                ('lang', models.ManyToManyField(to='complex.language')),
            ],
        ),
        migrations.CreateModel(
            name='PharentDistrict_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharentDistrict_en', models.CharField(max_length=50, unique=True)),
                ('city_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_en')),
                ('lang', models.ManyToManyField(to='complex.language')),
            ],
        ),
    ]
