# Generated by Django 4.2.7 on 2024-01-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex_en',
            name='catering_facility_en',
        ),
        migrations.RemoveField(
            model_name='complex_en',
            name='concierge_service_en',
        ),
        migrations.RemoveField(
            model_name='complex_en',
            name='elevator_type_en',
        ),
        migrations.RemoveField(
            model_name='complex_en',
            name='schlangbaum_en',
        ),
        migrations.RemoveField(
            model_name='complex_en',
            name='yard_description_en',
        ),
        migrations.RemoveField(
            model_name='complex_ka',
            name='catering_facility_ka',
        ),
        migrations.RemoveField(
            model_name='complex_ka',
            name='concierge_service_ka',
        ),
        migrations.RemoveField(
            model_name='complex_ka',
            name='elevator_type_ka',
        ),
        migrations.RemoveField(
            model_name='complex_ka',
            name='schlangbaum_ka',
        ),
        migrations.RemoveField(
            model_name='complex_ka',
            name='yard_description_ka',
        ),
        migrations.RemoveField(
            model_name='complex_ru',
            name='catering_facility_ru',
        ),
        migrations.RemoveField(
            model_name='complex_ru',
            name='concierge_service_ru',
        ),
        migrations.RemoveField(
            model_name='complex_ru',
            name='elevator_type_ru',
        ),
        migrations.RemoveField(
            model_name='complex_ru',
            name='schlangbaum_ru',
        ),
        migrations.RemoveField(
            model_name='complex_ru',
            name='yard_description_ru',
        ),
        migrations.AddField(
            model_name='complex_names',
            name='catering_facility_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='concierge_service_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='elevator_type_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='schlangbaum_ka',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complex_names',
            name='yard_description_ka',
            field=models.BooleanField(default=True),
        ),
    ]
