# Generated by Django 4.2.7 on 2024-01-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_rename_appartment_address_en_ground_en_ground_address_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground_ka',
            name='ground_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.ground_images'),
        ),
    ]
