# Generated by Django 4.2.7 on 2023-12-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_pharentdistrict_ru_pharentdistrict_ka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_ru', models.CharField(max_length=50, unique=True)),
                ('city_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ru')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ru')),
            ],
        ),
        migrations.CreateModel(
            name='District_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_ka', models.CharField(max_length=50, unique=True)),
                ('city_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ka')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka')),
            ],
        ),
        migrations.CreateModel(
            name='District_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_en', models.CharField(max_length=50, unique=True)),
                ('city_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_en')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_en')),
            ],
        ),
    ]
