# Generated by Django 4.2.7 on 2024-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_company_names_created_at_ground_names_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground_names',
            old_name='price',
            new_name='full_price',
        ),
        migrations.AddField(
            model_name='ground_names',
            name='square_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=12),
            preserve_default=False,
        ),
    ]
