# Generated by Django 4.2.7 on 2024-01-13 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_remove_complex_names_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment_names',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
