# Generated by Django 4.2.7 on 2023-11-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_remove_complex_complex_id_complex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='images',
        ),
        migrations.CreateModel(
            name='ComplexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complex_images/')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complex.complex')),
            ],
        ),
    ]
