# Generated by Django 4.2.7 on 2024-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_private_appartment_images_private_appartment_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_appartment_names',
            name='status',
            field=models.CharField(choices=[('1', 'Newly renovated'), ('2', 'with old repairs'), ('3', 'to be repaired')], default='3', max_length=30, null=True),
        ),
    ]
