# Generated by Django 4.2.7 on 2024-01-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_remove_complex_en_catering_facility_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complex_names',
            old_name='catering_facility_ka',
            new_name='catering_facility',
        ),
        migrations.RenameField(
            model_name='complex_names',
            old_name='concierge_service_ka',
            new_name='concierge_service',
        ),
        migrations.RenameField(
            model_name='complex_names',
            old_name='elevator_type_ka',
            new_name='elevator_type',
        ),
        migrations.RenameField(
            model_name='complex_names',
            old_name='schlangbaum_ka',
            new_name='schlangbaum',
        ),
        migrations.RenameField(
            model_name='complex_names',
            old_name='yard_description_ka',
            new_name='yard_description',
        ),
    ]
