# Generated by Django 4.2.7 on 2023-11-24 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_remove_company_aboutcompany_ka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_company', to='complex.company')),
            ],
        ),
    ]
