# Generated by Django 4.2.7 on 2023-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_remove_complex_names_finished_complex_names_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex_names',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
