# Generated by Django 4.2.7 on 2024-01-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_alter_complex_en_catering_facility_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex_en',
            name='nearby',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='complex_ka',
            name='nearby',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='complex_ru',
            name='nearby',
            field=models.JSONField(default=dict),
        ),
    ]
