# Generated by Django 4.2.7 on 2024-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_rename_price_ground_names_full_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground_names',
            name='status',
            field=models.CharField(choices=[('1', 'Agricultural'), ('2', 'Land for settlement'), ('3', 'Commercial')], default='3', max_length=50),
        ),
    ]
