# Generated by Django 4.2.7 on 2023-11-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_remove_complex_images_compleximage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplexImage',
        ),
    ]
