# Generated by Django 4.2.7 on 2024-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_appartment_names_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment_names',
            name='number_of_rooms',
            field=models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='studio', max_length=10),
        ),
    ]
