# Generated by Django 4.2.7 on 2024-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_rename_catering_facility_ka_complex_names_catering_facility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex_names',
            name='number_of_houses',
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='Pharmacy_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='Square_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='metro_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='supermarket_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='Description_ka',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='Pharmacy_ka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='Square_ka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='metro_ka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='supermarket_ka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='Pharmacy_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='Square_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='metro_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='supermarket_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
