# Generated by Django 4.2.7 on 2023-11-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_alter_complex_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex', to='complex.directaddress'),
        ),
    ]
