# Generated by Django 4.2.7 on 2023-12-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_district_ru_district_ka_district_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street_Name_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name_ru', models.CharField(max_length=50)),
                ('city_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ru')),
                ('district_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ka')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentstreet_name_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka')),
            ],
        ),
        migrations.CreateModel(
            name='Street_Name_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name_ka', models.CharField(max_length=50)),
                ('city_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ka')),
                ('district_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ka')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentstreet_name_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka')),
            ],
        ),
        migrations.CreateModel(
            name='Street_Name_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name_en', models.CharField(max_length=50)),
                ('city_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_en')),
                ('district_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ka')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentstreet_name_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka')),
            ],
        ),
    ]
