# Generated by Django 4.2.7 on 2024-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_alter_private_appartment_names_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_names',
            name='status',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Under Construction'), (3, 'Completed')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='private_appartment_names',
            name='status',
            field=models.CharField(choices=[('1', 'Newly renovated'), ('2', 'with old repairs'), ('3', 'to be repaired')], default='3', max_length=30),
        ),
    ]
