# Generated by Django 4.2.7 on 2024-01-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_complex_en_nearby_complex_ka_nearby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex_en',
            name='nearby_objects',
        ),
        migrations.RemoveField(
            model_name='complex_ka',
            name='nearby_objects',
        ),
        migrations.RemoveField(
            model_name='complex_ru',
            name='nearby_objects',
        ),
        migrations.DeleteModel(
            name='NearbyObject',
        ),
    ]
