# Generated by Django 4.2.7 on 2024-01-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_complex_names_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_names',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
