# Generated by Django 4.2.7 on 2024-01-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0004_alter_complex_names_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_names',
            name='status',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Under Construction'), (3, 'Completed')], default=2),
        ),
    ]
