# Generated by Django 4.2.7 on 2023-11-25 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0004_alter_complex_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compleximage',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complex.complex'),
        ),
    ]
