# Generated by Django 4.2.7 on 2024-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0004_remove_complex_names_number_of_houses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_en',
            name='Description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='construction_type_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='protection_type_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complex_en',
            name='submission_type_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='construction_type_ka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='protection_type_ka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='submission_type_ka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='Description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='construction_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='protection_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='submission_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
