# Generated by Django 4.2.7 on 2024-01-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0004_alter_appartment_names_number_of_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartment_names',
            old_name='price',
            new_name='full_price',
        ),
    ]
