# Generated by Django 4.2.7 on 2023-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0004_delete_compleximage'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='complex_images/'),
        ),
    ]
