# Generated by Django 4.2.7 on 2023-12-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0004_street_name_ru_street_name_ka_street_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street_name_en',
            old_name='pharentstreet_name_ka',
            new_name='pharentDistrict_en',
        ),
        migrations.RenameField(
            model_name='street_name_ka',
            old_name='pharentstreet_name_ka',
            new_name='pharentDistrict_ka',
        ),
        migrations.RenameField(
            model_name='street_name_ru',
            old_name='pharentstreet_name_ka',
            new_name='pharentDistrict_ru',
        ),
    ]
