# Generated by Django 4.2.7 on 2024-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0005_rename_price_appartment_names_full_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment_names',
            name='square_price',
            field=models.DecimalField(decimal_places=2, default=123.0, max_digits=10),
            preserve_default=False,
        ),
    ]
