# Generated by Django 4.2.7 on 2024-01-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0005_ground_names_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_ka',
            name='company_ka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_ka_complex_ka_set', to='complex.company_ka'),
        ),
    ]
