# Generated by Django 4.2.7 on 2023-11-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0005_alter_compleximage_complex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compleximage',
            old_name='image',
            new_name='images',
        ),
    ]
