# Generated by Django 4.2.7 on 2024-01-27 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0005_alter_complex_en_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_names',
            name='area_squareness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='complex_names',
            name='ceiling_height_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='complex_names',
            name='flooring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complex_names',
            name='humidity_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='complex_names',
            name='light_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='complex_names',
            name='number_of_buildings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complex_names',
            name='parking_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complex_names',
            name='rooms_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
