# Generated by Django 4.2.7 on 2023-12-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0005_rename_pharentstreet_name_ka_street_name_en_pharentdistrict_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Name_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_num_ru', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ru')),
                ('district_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ru')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka')),
                ('street_name_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.street_name_ru')),
            ],
        ),
        migrations.CreateModel(
            name='Address_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_num_ka', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_ka')),
                ('district_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_ka')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka')),
                ('street_name_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.street_name_ka')),
            ],
        ),
        migrations.CreateModel(
            name='Address_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_num_en', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.city_en')),
                ('district_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.district_en')),
                ('lang', models.ManyToManyField(to='complex.language')),
                ('pharentDistrict_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ka')),
                ('street_name_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.street_name_en')),
            ],
        ),
    ]
