# Generated by Django 4.2.7 on 2024-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0005_complex_names_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex_names',
            name='rank',
            field=models.CharField(choices=[('A', 'Rank A'), ('B', 'Rank B'), ('C', 'Rank C'), ('D', 'Rank D'), ('E', 'Rank E')], default='E', max_length=1),
        ),
    ]
