# Generated by Django 4.2.7 on 2024-01-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0006_alter_complex_ka_company_ka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_ka',
            name='company_ka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.company_ka'),
        ),
    ]
