# Generated by Django 4.2.7 on 2023-11-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0006_remove_complex_images_compleximage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('Mobile', models.CharField(max_length=20)),
                ('Mobile_Home', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('companyweb', models.URLField(blank=True, null=True)),
                ('aboutcompany', models.TextField(blank=True, null=True)),
                ('logocompany', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
        migrations.AddField(
            model_name='complex',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complex.company'),
            preserve_default=False,
        ),
    ]
