# Generated by Django 4.2.7 on 2023-12-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0006_address_name_ru_address_ka_address_en'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address_Name_RU',
            new_name='Address_RU',
        ),
        migrations.RenameField(
            model_name='address_en',
            old_name='address_num_en',
            new_name='address_en',
        ),
        migrations.RenameField(
            model_name='address_ka',
            old_name='address_num_ka',
            new_name='address_ka',
        ),
        migrations.RenameField(
            model_name='address_ru',
            old_name='address_num_ru',
            new_name='address_ru',
        ),
    ]
