# Generated by Django 4.2.7 on 2023-11-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_locations', '0001_initial'),
        ('complex', '0006_remove_complex_images_compleximage'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='city_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='city_locations.citylocations'),
            preserve_default=False,
        ),
    ]
