# Generated by Django 4.2.7 on 2024-01-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0006_alter_complex_names_area_squareness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_images',
            name='images',
            field=models.ImageField(upload_to='complex_images/'),
        ),
    ]
