# Generated by Django 4.2.7 on 2024-01-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0006_appartment_names_square_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_names',
            name='vip_company',
            field=models.BooleanField(default=False),
        ),
    ]
