# Generated by Django 4.2.7 on 2024-01-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0007_company_names_vip_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment_names',
            name='status',
            field=models.CharField(choices=[('1', 'Newly renovated'), ('2', 'with old repairs'), ('3', 'to be repaired')], default='3', max_length=30),
        ),
    ]
