# Generated by Django 4.2.7 on 2024-01-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0007_alter_complex_names_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex_names',
            name='complex_level',
        ),
    ]
