# Generated by Django 4.2.7 on 2023-11-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_locations', '0002_citylocations_level_citylocations_lft_and_more'),
        ('complex', '0007_complex_city_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='city_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='city_locations.citylocations'),
        ),
    ]
