# Generated by Django 4.2.7 on 2023-12-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0007_rename_address_name_ru_address_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logocompany', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='company_background_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=20)),
                ('Mobile_Home', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('companyweb', models.URLField(blank=True, null=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_images')),
            ],
        ),
        migrations.CreateModel(
            name='Company_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('address_ru', models.TextField()),
                ('aboutcompany_ru', models.TextField(blank=True, null=True)),
                ('internal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_names')),
            ],
        ),
        migrations.CreateModel(
            name='Company_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=255)),
                ('address_ka', models.TextField()),
                ('aboutcompany_ka', models.TextField(blank=True, null=True)),
                ('internal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_names')),
            ],
        ),
        migrations.AddField(
            model_name='company_images',
            name='internal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_names'),
        ),
        migrations.CreateModel(
            name='Company_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('address_en', models.TextField()),
                ('aboutcompany_en', models.TextField(blank=True, null=True)),
                ('internal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_names')),
            ],
        ),
    ]
