# Generated by Django 4.2.7 on 2023-11-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0008_company_background_image_company_facebook_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='complex.company'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('floor_number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='complex.complex')),
            ],
        ),
    ]
