# Generated by Django 4.2.7 on 2024-01-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0008_appartment_names_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Private_Appartment_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='private_apartment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Private_Appartment_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_private_appartment_name', models.CharField(max_length=50)),
                ('number_of_rooms', models.CharField(choices=[('studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='studio', max_length=10)),
                ('status', models.CharField(choices=[('1', 'Newly renovated'), ('2', 'with old repairs'), ('3', 'to be repaired')], default='3', max_length=30)),
                ('area', models.DecimalField(decimal_places=2, max_digits=7)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('square_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor_number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('visibiliti', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company_names',
            name='vip_company',
        ),
        migrations.CreateModel(
            name='Private_Appartment_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_appartment_name_ru', models.CharField(max_length=100, null=True)),
                ('test_private_field_ru', models.CharField(max_length=100)),
                ('internal_private_appartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_names')),
                ('private_appartment_address_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.address_ru')),
                ('private_appartment_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_images')),
            ],
        ),
        migrations.CreateModel(
            name='Private_Appartment_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_appartment_name_ka', models.CharField(max_length=100, null=True)),
                ('test_private_field_ka', models.CharField(max_length=100)),
                ('internal_private_appartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_names')),
                ('private_appartment_address_ka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.address_ka')),
                ('private_appartment_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_images')),
            ],
        ),
        migrations.AddField(
            model_name='private_appartment_images',
            name='internal_private_apartment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_names'),
        ),
        migrations.CreateModel(
            name='Private_Appartment_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_appartment_name_en', models.CharField(max_length=100, null=True)),
                ('test_private_field_en', models.CharField(max_length=100)),
                ('internal_private_appartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_names')),
                ('private_appartment_address_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.address_en')),
                ('private_appartment_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complex.private_appartment_images')),
            ],
        ),
    ]
