# Generated by Django 4.2.7 on 2023-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0008_alter_complex_city_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compleximage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
