# Generated by Django 4.2.7 on 2023-12-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0008_company_images_company_names_company_ru_company_ka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_names',
            name='images',
        ),
    ]
