# Generated by Django 4.2.7 on 2023-11-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0008_company_aboutcompany_en_company_aboutcompany_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
