# Generated by Django 4.2.7 on 2023-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0009_alter_complex_company_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='complex_id',
            field=models.ManyToManyField(blank=True, related_name='company_complexes', to='complex.complex'),
        ),
    ]
