# Generated by Django 4.1.7 on 2023-11-20 21:01

from django.db import migrations, models
import django.db.models.deletion
import djangoarrayfield.fields
import djangoarrayfield.serializers


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0009_alter_complex_company_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='images',
            field=djangoarrayfield.fields.DjangoArrayField(blank=True, decoder=djangoarrayfield.serializers.DjangoArrayDecoder, encoder=djangoarrayfield.serializers.DjangoArrayEncoder, null=True, verbose_name=models.ImageField(upload_to='complex_images/')),
        ),
        migrations.AlterField(
            model_name='compleximage',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_images', to='complex.complex'),
        ),
    ]
