# Generated by Django 4.2.7 on 2023-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0009_alter_city_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='directaddress',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='directaddress',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='directaddress',
            name='street',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pharentdistrict',
            name='pharentDistrict',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
