# Generated by Django 4.2.7 on 2023-12-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0009_remove_company_names_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_names',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company_en',
            name='internal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_images'),
        ),
        migrations.AlterField(
            model_name='company_ka',
            name='internal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_images'),
        ),
        migrations.AlterField(
            model_name='company_ru',
            name='internal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_images'),
        ),
    ]
