# Generated by Django 4.2.7 on 2023-11-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0009_alter_complex_company_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='complex_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
