# Generated by Django 4.2.7 on 2024-01-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0009_private_appartment_images_private_appartment_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='private_appartment_en',
            old_name='internal_private_appartment_name',
            new_name='internal_private_apartment_name',
        ),
        migrations.RenameField(
            model_name='private_appartment_en',
            old_name='private_appartment_address_en',
            new_name='private_apartment_address_en',
        ),
        migrations.RenameField(
            model_name='private_appartment_en',
            old_name='private_appartment_images',
            new_name='private_apartment_images',
        ),
        migrations.RenameField(
            model_name='private_appartment_en',
            old_name='private_appartment_name_en',
            new_name='private_apartment_name_en',
        ),
        migrations.RenameField(
            model_name='private_appartment_ka',
            old_name='internal_private_appartment_name',
            new_name='internal_private_apartment_name',
        ),
        migrations.RenameField(
            model_name='private_appartment_ka',
            old_name='private_appartment_address_ka',
            new_name='private_apartment_address_ka',
        ),
        migrations.RenameField(
            model_name='private_appartment_ka',
            old_name='private_appartment_images',
            new_name='private_apartment_images',
        ),
        migrations.RenameField(
            model_name='private_appartment_ka',
            old_name='private_appartment_name_ka',
            new_name='private_apartment_name_ka',
        ),
        migrations.RenameField(
            model_name='private_appartment_ru',
            old_name='internal_private_appartment_name',
            new_name='internal_private_apartment_name',
        ),
        migrations.RenameField(
            model_name='private_appartment_ru',
            old_name='private_appartment_address_ru',
            new_name='private_apartment_address_ru',
        ),
        migrations.RenameField(
            model_name='private_appartment_ru',
            old_name='private_appartment_images',
            new_name='private_apartment_images',
        ),
        migrations.RenameField(
            model_name='private_appartment_ru',
            old_name='private_appartment_name_ru',
            new_name='private_apartment_name_ru',
        ),
    ]
