# Generated by Django 4.2.7 on 2023-11-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_locations', '0004_rename_parent_citylocations_parentid'),
        ('complex', '0009_alter_compleximage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='city_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='city_locations.citylocations'),
        ),
    ]
