# Generated by Django 4.2.7 on 2023-11-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0010_company_complex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='complex_id',
        ),
        migrations.AddField(
            model_name='company',
            name='complex_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_complexes', to='complex.complex'),
            preserve_default=False,
        ),
    ]
