# Generated by Django 4.2.7 on 2024-01-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0010_rename_internal_private_appartment_name_private_appartment_en_internal_private_apartment_name_and_mo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='private_appartment_names',
            old_name='internal_private_appartment_name',
            new_name='internal_private_apartment_name',
        ),
    ]
