# Generated by Django 4.2.7 on 2023-11-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0010_complex_complex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='complex_id',
        ),
    ]
