# Generated by Django 4.1.7 on 2023-11-20 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0010_complex_images_alter_compleximage_complex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='complex.company'),
        ),
    ]
