# Generated by Django 4.2.7 on 2023-12-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0010_company_names_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='complex_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Complex_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Internatl_complex_name', models.CharField(max_length=255)),
                ('price_per_sq_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finished', models.BooleanField()),
                ('vipComplex', models.BooleanField()),
                ('space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_apartments', models.IntegerField()),
                ('number_of_houses', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Complex_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name_ru', models.CharField(max_length=200)),
                ('type_of_roof_ru', models.CharField(max_length=100)),
                ('Internatl_complex_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_images')),
                ('address_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.address_ru')),
                ('company_ru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_ru')),
            ],
        ),
        migrations.CreateModel(
            name='Complex_KA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name_ka', models.CharField(max_length=200)),
                ('type_of_roof_ka', models.CharField(max_length=100)),
                ('Internatl_complex_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_images')),
                ('address_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.address_ka')),
                ('company_ka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_ka')),
            ],
        ),
        migrations.AddField(
            model_name='complex_images',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_names'),
        ),
        migrations.CreateModel(
            name='Complex_EN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_name_en', models.CharField(max_length=200)),
                ('type_of_roof_en', models.CharField(max_length=100)),
                ('Internatl_complex_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex_images')),
                ('address_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.address_en')),
                ('company_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.company_en')),
            ],
        ),
    ]
