# Generated by Django 4.2.7 on 2023-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0011_remove_company_complex_id_company_complex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='complex_id',
        ),
        migrations.AddField(
            model_name='company',
            name='complex_id',
            field=models.ManyToManyField(blank=True, related_name='company_complexes', to='complex.complex'),
        ),
    ]
