# Generated by Django 4.2.7 on 2023-11-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0011_remove_complex_complex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex', to='complex.company'),
        ),
    ]
