# Generated by Django 4.2.7 on 2023-12-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0011_complex_images_complex_names_complex_ru_complex_ka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex_names',
            name='visibiliti',
            field=models.BooleanField(default=True),
        ),
    ]
