# Generated by Django 4.2.7 on 2023-12-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0012_complex_names_visibiliti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_images',
            name='background_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='company_background_images/'),
        ),
        migrations.AlterField(
            model_name='company_images',
            name='logocompany',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='complex_images',
            name='images',
            field=models.ImageField(unique=True, upload_to='complex_images/'),
        ),
    ]
