# Generated by Django 4.2.7 on 2023-11-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0012_remove_company_complex_id_company_complex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='complex_id',
        ),
    ]
