# Generated by Django 4.2.7 on 2023-12-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0013_alter_company_images_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complex_en',
            old_name='Internatl_complex_name',
            new_name='Internal_complex_name',
        ),
        migrations.RenameField(
            model_name='complex_ka',
            old_name='Internatl_complex_name',
            new_name='Internal_complex_name',
        ),
        migrations.RenameField(
            model_name='complex_names',
            old_name='Internatl_complex_name',
            new_name='Internal_complex_name',
        ),
        migrations.RenameField(
            model_name='complex_ru',
            old_name='Internatl_complex_name',
            new_name='Internal_complex_name',
        ),
    ]
