# Generated by Django 4.2.7 on 2023-12-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0014_rename_internatl_complex_name_complex_en_internal_complex_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complex_en',
            old_name='Internal_complex_name',
            new_name='internal_complex_name',
        ),
        migrations.RenameField(
            model_name='complex_ka',
            old_name='Internal_complex_name',
            new_name='internal_complex_name',
        ),
        migrations.RenameField(
            model_name='complex_names',
            old_name='Internal_complex_name',
            new_name='internal_complex_name',
        ),
        migrations.RenameField(
            model_name='complex_ru',
            old_name='Internal_complex_name',
            new_name='internal_complex_name',
        ),
    ]
