# Generated by Django 4.2.7 on 2023-12-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0015_rename_internal_complex_name_complex_en_internal_complex_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex_en',
            name='complex_name_en',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='complex_ka',
            name='complex_name_ka',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='complex_names',
            name='internal_complex_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='complex_ru',
            name='complex_name_ru',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
