# Generated by Django 4.2.7 on 2023-12-04 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0016_alter_complex_en_complex_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_en',
            name='pharentDistrict_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_en'),
        ),
        migrations.AlterField(
            model_name='address_ru',
            name='pharentDistrict_ru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.pharentdistrict_ru'),
        ),
    ]
