# Generated by Django 4.2.7 on 2023-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_locations', '0002_citylocations_level_citylocations_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocations',
            name='name',
            field=models.CharField(help_text='Enter the name of the city.', max_length=200),
        ),
    ]
