# Generated by Django 4.2.7 on 2023-11-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_locations', '0003_alter_citylocations_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citylocations',
            old_name='parent',
            new_name='parentId',
        ),
    ]
