# Generated by Django 4.2.7 on 2023-11-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_locations', '0004_rename_parent_citylocations_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citylocations',
            old_name='parentId',
            new_name='parent',
        ),
    ]
